cy.APP_STATUSES = {
    UC: "UC",
    CC: "CC",
    CL: "CL",
    EN: "EN",
    ER: "ER",
    PN: "PN",
    OP: "OP",
    SU: "SU",
    SG: "SG",
    QU: "QU"
}

cy.APP_TYPES = {
    SEP: "SEP",
    QEP: "QEP",
    OE: "OE"
}

cy.VALIDATION_STATUSES = {
    NOTREQUIRED: "NOTREQUIRED",
    PENDING: "PENDING",
    PENDING_INFO: "PENDING_INFO"
}

cy.FURTHER_ACTION_LINKS = {
    START_NEW_APPLICATION: "START_NEW_APPLICATION",
    RESUME_APPLICATION: "RESUME_APPLICATION",
    GROUPING_SCREEN: "GROUPING_SCREEN",
    GROUPING_SCREEN_IF_ALL_ENROLLMENTS_NOT_WITHIN_THIS_MONTH: "GROUPING_SCREEN_IF_ALL_ENROLLMENTS_NOT_WITHIN_THIS_MONTH",
    REPORT_CHANGE: "REPORT_CHANGE",
    REPORT_LIFE_EVENT_SHOP: "REPORT_LIFE_EVENT_SHOP",
    UPLOAD_DOCUMENTS: "UPLOAD_DOCUMENTS",
    CONFIRM_EVENT: "CONFIRM_EVENT",
    VERIFICATION: "VERIFICATION",
    SHOPPING_CART: "SHOPPING_CART",
    CONTINUE: "CONTINUE",
    CONTACT_US: "CONTACT_US"
}

cy.WARNING_TYPES = {
    WARNING: "WARNING",
    ALERT: "ALERT",
    ANNOUNCEMENT: "ANNOUNCEMENT"
}

