module.exports = {
 healthPlansHeader: "Health Plans",
 Summary : "Summary",
 DeductibleOOP :  "Deductible & Out-of-Pocket",
 DoctorVisit : "Doctor Visit",
 Tests : "Tests",
 Drugs : "Drugs",
 OutPatient : "Outpatient",
 ERUrgent : "ER & Urgent Care",
 Hospital : "Hospital",
 MentalBehavioral : "Mental / Behavioral Health",
 Pregnancy : "Pregnancy",
 SpecialNeeds : "Other Special Needs",
 ChildrenVision : "Children's Vision",
 ChildrenDental : "Children's Dental",
 add: "ADD",
 dentalPlans: "Dental Plans",
 backToPreferences: "Back to preferences",
 editFamilyInfo: "Edit Family Info",
 ZIP: "ZIP",
 memberInfo: "Member",
 sortByHeading: "SORT BY",
 filterByHeading: "FILTER BY",
 label_expenseEstimate: "Expense Estimate",
 label_monthlyPrice: "Monthly price",
 label_deductible: "Deductible",
 label_OOP: "Out-of-Pocket (OOP) Max",
 label_planType: "PLAN TYPE",
 label_HMO: "HMO",
 label_planFeature: "PLAN FEATURES",
 label_HSA: "HSA",
 label_metalTier: "METAL TIER",
 label_Platinum: "Platinum",
 label_Gold: "Gold",
 label_Silver: "Silver",
 label_Bronze: "Bronze",
 label_deductible: "DEDUCTIBLE",
 label_2500: "$2500 and less",
 label_5000: "$5000 and less",
 label_company: "COMPANY",
 label_compare: "COMPARE",
 label_detail: "DETAILS",
 label_add: "ADD"




}