module.exports = {
    
    //Preeligibility Page 
    needsCoverage:"Check the box if this family member wants health insurance.",
    nativeAmerican:"Members of Federally Recognized American Indian or Alaska Native Tribes may be eligible for special benefits and protections through MNsure."+
    " For example, members of a federally-recognized tribe who enroll in a plan through MNsure and have an income at or below 300 percent of the federal poverty level may"+
        " be eligible for 100% cost-sharing benefits, which means they are not required to pay deductibles, co-payments, or other out-of-pocket costs."+
            " Also, there is no cost-sharing for services provided by Indian health care providers (I/T/U). This online tool cannot make these calculations. "+
            "To understand the full benefits that may be available to you, please call the MNsure Contact Center for assistance at 1-855-366-7873 (1-855-3MNSURE). ",
    tobaccoUse:"Check the box if this family member used tobacco regularly (4 or more times per week) over the last 6 months.",
    taxHouseholdIncome:"This is the total income for everyone listed on your tax return.",
    
    //Pre eligibility Results page
    coInsurance:"Your share of the costs of a covered health care service, calculated as a percent (for example, 20%) of the allowed amount for the service. You pay co-insurance plus any deductibles you owe. For example, if the health insurance or plan's allowed amount for an office visit is $100 and you've met your deductible, your co-insurance payment of 20% would be $20. The health insurance or plan pays the rest of the allowed amount.",
    coPay :"A co-payment, or co-pay, is a fixed amount you pay for a covered healthcare service, usually at the time you use the service.",
    deductible : "Your plan's deductible is the dollar amount you have to spend on your covered medical expenses before your insurance company starts to help pay. Generally, co-pays are not counted toward your deductible.",
    
    ////Preferences Page
    medicalService : "Your medical service use level helps estimate what you could spend when you see a doctor or get other care (for doctors and hospitals in the plan’s network). To see how plans compare if your health is better or worse next year, return to the screen and change your selection.",
    prescriptionDrug : "Your prescription drug use level is used to estimate what you spend when you buy medications (for drugs covered by the plan). To see how plans compare if your health is better or worse next year, return to the screen and change your selection.",
    doYouKnow:"There may be multiple brand and generic medications that address the same health issue. Generic options cost less than the brand name drugs and are typically covered by a larger number of health plans. By considering generic drugs you may save money and expand the number of plans available to you, some of which may better fit your budget. Please consult with your doctor to determine if a generic is right for you.",
    childrenDental:"Children's dental is considered an essential health benefit - which means it must be available for you to buy. But that doesn't mean that every single health insurance plan will have children's dental built in. With some plans, you'll have to buy children's dental separately. Check 'Children's Dental' if you'd prefer to see plans that have children's dental coverage built in.",
    hsaEligible:"Health Savings Accounts (HSAs) are savings accounts available through some high-deductible health plans as a way to save money for certain medical expenses. The funds contributed to the account aren’t subject to federal income tax at the time of deposit. Funds must be used to pay for qualified medical expenses, such as prescription drugs. Unlike a Flexible Spending Account (FSA), the funds in HSAs roll over year to year if you don’t spend them.",
    
    //Health Plan Display Page
    EPO:"An Exclusive Provider Organization (EPO) plan is a managed care plan where services are covered only if you use doctors, specialists or hospitals in the plan's network (except in an emergency).",
    HMO:"A Health Maintenance Organization (HMO) plan is a type of health insurance plan that usually limits coverage to care from doctors who work for or contract with the HMO. It generally won't cover out-of-network care except in an emergency. An HMO may require you to live or work in its service area to be eligible for coverage. HMOs often provide integrated care and focus on prevention and wellness.",
    PPO:"A Preferred Provider Organization (PPO) plan includes a network of health care providers with which a health insurer has negotiated contracts for its insured population to receive health services at discounted costs. Health care decisions generally remain with the patient as he or she selects providers and determines his or her own need for services. Patients have financial incentives to select providers within the PPO network.",
    POS:"POS stands for \"point of service\". With a POS plan you pay less if you use doctors, hospitals, and other health care providers that belong to the plan's network. If you go out-of-network, your plan will provide coverage, but it will likely cost you more. You will also need a referral for a specialist.",
    psEligibilityAmount:"A monthly tax credit (also known as an Advanced Premium Tax Credit) helps eligible consumers with low or moderate income pay for health insurance.",
    CSR:"Cost-sharing reductions (CSR) are a form of financial help that help to reduce the out-of-pocket costs associated with private health insurance, such as deductibles, co-insurance and co-payments. If you qualify for cost-sharing reductions, you can only get those savings if you pick a silver plan. (This silver plan limit does not apply to members of federally recognized tribes.)",
    CSREligible:"Cost-sharing reductions (CSR) are a form of financial help that help to reduce the out-of-pocket costs associated with private health insurance, such as deductibles, co-insurance and co-payments. If you qualify for cost-sharing reductions, you can only get those savings if you pick a silver plan. (This silver plan limit does not apply to members of federally recognized tribes.)",
    HSAEligible:"Health Savings Accounts (HSAs) are savings accounts available through some high-deductible health plans as a way to save money for certain medical expenses. The funds contributed to the account aren’t subject to federal income tax at the time of deposit. Funds must be used to pay for qualified medical expenses, such as prescription drugs. Unlike a Flexible Spending Account (FSA), the funds in HSAs roll over year to year if you don’t spend them.",
    metalLevel:"Most medical plans are categorized as one of four metal levels. These levels are based on how you and your plan split the costs of your health care.",
    yearlyDeductible:"The amount you pay for covered services before your insurance plan will reimburse any expenses for in-network services. Not all payments count against the deductible.",
    Catastrophic:"Catastrophic plans have high deductibles. The benefit level on a catastrophic plan is even less than the bronze metal level plan. You must be under 30 years old or qualify for a hardship exemption to purchase a catastrophic plan",
    primaryCareVisits:"Estimated co-pay or co-insurance to visit a health care office or facility where services are provided by a physician, nurse practitioner or physician assistant to treat an injury or illness. Click the plan's DETAILS link to see how the co-pay or co-insurance is applied.",
    genericDrugs:"A prescription drug that has the same active-ingredient formula as a brand-name drug. Generic drugs usually cost less than brand-name drugs. The Food and Drug Administration (FDA) rates these drugs to be as safe and effective as brand-name drugs. Click the plan's DETAILS link to see how the Generic Drug co-pay or co-insurance is applied.",
    cp_tile:"This is an estimate of the total yearly expense level you may incur for this plan. This includes your share of the premium for the plan year and an estimate of what you pay when you get care - like the amount you spend when you visit the doctor, get a lab test or buy a prescription drug. These estimates are for network doctors and hospitals only; out-of-network providers cost more.",
    OutOfPocketMax:"The most you could pay during a coverage period (usually one year) for your share of the costs of covered services. After you meet this limit the plan will usually pay 100% of the allowed amount. This limit helps you plan for health care costs. This limit never includes your premium, balance-billed charges or health care your plan doesn’t cover. Some plans don’t count all of your co-payments, deductibles, co-insurance payments, out-of-network payments, or other expenses toward this limit.",
    //Plan Details Page
    
    HSACompatible:"A medical savings account available to taxpayers who are enrolled in a qualified high deductible health plan. The funds contributed to the account aren't subject to federal income tax at the time of deposit. Funds must be used to pay for qualified medical expenses. Unlike a flexible spending account (FSA), funds roll over year to year if you don't spend them.",
    outOfPocketMaximum:"The most you could pay during a coverage period (usually one year) for your share of the costs of covered services. After you meet this limit the plan will usually pay 100% of the allowed amount. This limit helps you plan for health care costs. This limit never includes your premium, balance-billed charges or health care your plan doesn’t cover. Some plans don’t count all of your co-payments, deductibles, co-insurance payments, out-of-network payments, or other expenses toward this limit.",   
    specialistVisit:"A physician specialist focuses on a specific area of medicine or a group of patients to diagnose, manage, prevent or treat certain types of symptoms and conditions. A non-physician specialist is a provider who has more training in a specific area of health care.",
    otherPractitionerOfficeVisit:"Office visits for services from other health care providers such as  registered dieticians or  physical therapists.",
    preventiveCare:"Routine health care that includes screenings, check-ups and patient counseling to prevent illnesses, disease or other health problems.",
    inpatientHospitalServices:"Care in a hospital that requires admission and usually requires an overnight stay.",
    inNetwork:"The plan's primary provider network.  Seeing health care providers that are in-network will result in lower out-of-pocket costs.",
    outofNetwork:"A provider who doesn't have a contract with your plan to provide services. If your plan covers out-of-network services, you'll usually pay more to see an out-of-network provider than a preferred provider.",
    totalExpenseEstimate:"This is an estimate of the total yearly expense level you may incur for this plan. This includes your share of the premium for the plan year and an estimate of what you pay when you get care - like the amount you spend when you visit the doctor, get a lab test or buy a prescription drug. These estimates are for network doctors and hospitals only; out-of-network providers cost more. These estimates, which are for all covered medical services, are based on your answers about expected doctor visits and prescription drug use. If you did not answer these questions, we assume that you have 'moderate' health care needs.",
    primaryCareVisit:"Estimated co-pay or co-insurance to visit a health care office or facility where services are provided by a physician, nurse practitioner or physician assistant to treat an injury or illness.",
    genericDrug:"A prescription drug that has the same active-ingredient formula as a brand-name drug. Generic drugs usually cost less than brand-name drugs. The Food and Drug Administration (FDA) rates these drugs to be as safe and effective as brand-name drugs.",
    //YearlyDeductible:"The most you could pay during a coverage period (usually one year) for your share of the costs of covered services. After you meet this limit the plan will usually pay 100% of the allowed amount. This limit helps you plan for health care costs. This limit never includes your premium, balance-billed charges or health care your plan doesn’t cover. Some plans don’t count all of your co-payments, deductibles, co-insurance payments, out-of-network payments, or other expenses toward this limit.",
    YearlyDeductible:"The amount you pay for covered services before your insurance plan will reimburse any expenses for in-network services. Not all payments count against the deductible.",
    //Dental Plan Display Page
    PPO:"A Preferred Provider Organization (PPO) plan includes a network of health care providers with which a health insurer has negotiated contracts for its insured population to receive health services at discounted costs. Health care decisions generally remain with the patient as he or she selects providers and determines his or her own need for services. Patients have financial incentives to select providers within the PPO network.",
    Low:"The low coverage level has lower premiums but higher copayments and deductibles. This means you will typically pay less in premiums each month, but you will pay more when you use dental services.",
    High:"The high coverage level has higher premiums but lower copayments and deductibles. This means you will typically pay more in premiums each month, but you will pay less when you use dental services.",
    inNetworkDental:"The plan's primary provider network.  Seeing health care providers that are in-network will result in lower out-of-pocket costs.",
    yearlyDeductibleChild:"The amount you pay for covered services before your insurance plan will reimburse any expenses for in-network services. Not all payments count against the deductible.",
    OutOfPocketMaxDental:"The most you could pay during a coverage period (usually one year) for your share of the costs of covered services. After you meet this limit the plan will usually pay 100% of the allowed amount. This limit never includes your premium, balance-billed charges or dental care your plan doesn't cover. Some plans don't count all of your copayments, deductibles, coinsurance payments, out-of-network payments, or other expenses toward this limit.",
    details:"test",
    TotalMonthlyDue:"test",
      //  var $message = "Member Level PremiumMember age "+$ageTwo+" "+"$"+$planPremiumTwo+" Member age "+$ageOne+" "+"$"+$planPremiumOne+" Total"+" "+"$"+$totalPremium+"APTC-"+"$"+$aptc+"Net Premium"+"$"+$netPremium;
    
//Dental details Page:    
    
//	$message = "Member Level PremiumMember age " + $ageTwo + " " + "$" + $planPremium + " Member age " + $ageOne + " " + "$" + $planPremium + " Total"+" "+"$"+ $totalPremium + "APTC-" + "$" + "0.00" + "Net Premium" + "$" + $totalPremium;
//verifyTooltip(_link("Details"), $message);  

//Dental compare
planType:"The type of health plan you choose determines your in- and out-of-network benefits. Common types include HMO, EPO, PPO, and POS.",
PPO1:"A Preferred Provider Organization (PPO) plan includes a network of health care providers with which a health insurer has negotiated contracts for its insured population to receive health services at discounted costs. Health care decisions generally remain with the patient as he or she selects providers and determines his or her own need for services. Patients have financial incentives to select providers within the PPO network.",

//Health Compare:
totalExpenseEstimate:"This is an estimate of the total yearly expense level you may incur for this plan. This includes your share of the premium for the plan year and an estimate of what you pay when you get care - like the amount you spend when you visit the doctor, get a lab test or buy a prescription drug. These estimates are for network doctors and hospitals only; out-of-network providers cost more. These estimates, which are for all covered medical services, are based on your answers about expected doctor visits and prescription drug use. If you did not answer these questions, we assume that you have 'moderate' health care needs.",
PlanType:"The type of health plan you choose determines your in- and out-of-network benefits. Common types include HMO, EPO, PPO, and POS.",

 
 }